### ISSUE TITLE
TUIPopover Deallocation Issues

### ISSUE THREAD

**Issue by CodaFi** [github/twui#147] opened 2012-12-09 21:18 UTC
TUIPopover functions fine normally with a simple TUIView as it's content view controller, but when subviews, especially tableviews, are added to said content view controller, TUIPopover begins to release wildly in one of a few ways I've observed (interestingly enough, this is fixed by #143):

1) (Using only a tableview), the window is closed, it's contentView is then nilled out (unnecessarily, IMHO), which then causes a `-release` to be sent twice to the contentView.

2) (Sans tableview), the window is closed, sent the proper release messages, then TUIPopover sends it a second release (a release to an unallocated pointer).

3) (Sans TableView, with a background view), the window is closed, sent the proper release message, then TUIPopover sends it's background view an extra release.

**Comment by avaidyam** [comment] 2012-12-09 23:43
@CodaFi I believe I fixed these issues by not setting `self.popoverWindow.contentView = nil;`, and set `[self.popoverWindow setReleasedOnClose:YES];` or something. I don't remember exactly what, and I can answer more precisely when I finish getting my Mac ready for development... :unamused:

**Comment by jwilling** [comment] 2012-12-10 14:23
Do you have a small demo project that demonstrates this behavior?

**Comment by CodaFi** [comment] 2012-12-10 16:35
@jwilling Yeah, I call her [crashy](https://www.dropbox.com/s/aox81lrtng9oy1r/Crashy.zip).

**Comment by jwilling** [comment] 2012-12-10 19:50
I believe the problem is that there is a retain cycle on the completion block on [line 279](https://github.com/github/twui/blob/master/lib/UIKit/TUIPopover.m#L279). This is preventing the root view of the `TUINSView` in `TUIPopoverWindowContentView` from being deallocated, which is causing the deallocation issue.

This can be easily resolved by either fixing the retain cycle as noted above, or by explicitly setting the `rootView` of the `TUINSView` to nil in `dealloc` (in `TUIPopoverWindowContentView`).

//cc @dannygreg

**Comment by jwilling** [comment] 2012-12-11 18:09
Fixed by #148.

**Closed as completed by jwilling** 2012-12-11 18:09 UTC

**Comment by dannygreg** [comment] 2012-12-11 18:21
Now that's how you fix a bug folks. A one line change……… rather than a complete rewrite of everything.

**Comment by avaidyam** [comment] 2012-12-11 18:40
Hehe xD :panda_face:
